-- AI-Enhanced Schema Migration
-- This migration adds AI-specific tables and enhances existing ones for intelligent financial analysis

-- Add new enum types
CREATE TYPE automation_level AS ENUM ('MANUAL', 'AI_SUGGESTED', 'AI_AUTOMATED', 'AI_LEARNED');
CREATE TYPE insight_type AS ENUM ('OPPORTUNITY', 'RISK', 'OPTIMIZATION', 'PREDICTION', 'ANOMALY', 'BENCHMARK');
CREATE TYPE insight_priority AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW');

-- Business Context table for rich AI metadata
CREATE TABLE business_context (
    id VARCHAR(255) PRIMARY KEY,
    entry_id VARCHAR(255) UNIQUE NOT NULL,
    tenant_id VARCHAR(255) NOT NULL,
    
    -- Business Dimensions
    business_unit VARCHAR(255),
    project VARCHAR(255),
    campaign VARCHAR(255),
    channel VARCHAR(255),
    territory VARCHAR(255),
    
    -- Customer/Vendor Intelligence
    entity_segment VARCHAR(255),
    entity_tier VARCHAR(255),
    relationship_length INTEGER,
    lifetime_value DECIMAL(15,2),
    payment_history JSON,
    risk_profile VARCHAR(255),
    
    -- Contextual Metadata
    market_conditions JSON,
    competitor_analysis JSON,
    seasonal_factors JSON,
    external_events JSON,
    
    -- AI Learning Data
    user_decision_patterns JSON,
    correction_history JSON,
    prediction_accuracy JSON,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (entry_id) REFERENCES entries(id) ON DELETE CASCADE,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    
    INDEX idx_business_context_tenant (tenant_id),
    INDEX idx_business_context_segment (tenant_id, entity_segment),
    INDEX idx_business_context_business_unit (tenant_id, business_unit),
    INDEX idx_business_context_composite (tenant_id, entity_segment, business_unit, created_at)
);

-- AI Model Performance tracking
CREATE TABLE ai_model_performance (
    id VARCHAR(255) PRIMARY KEY,
    model_type VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255) NOT NULL,
    
    -- Performance Metrics
    accuracy FLOAT,
    precision_score FLOAT,
    recall_score FLOAT,
    f1_score FLOAT,
    
    -- Business Metrics
    times_saved INTEGER DEFAULT 0,
    errors_detected INTEGER DEFAULT 0,
    revenue_impact DECIMAL(15,2),
    
    -- Learning Progression
    training_data_points INTEGER,
    last_training_date TIMESTAMP,
    improvement_rate FLOAT,
    
    period TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    
    INDEX idx_ai_performance_tenant (tenant_id),
    INDEX idx_ai_performance_model (tenant_id, model_type),
    INDEX idx_ai_performance_period (tenant_id, period)
);

-- Business Insights generated by AI
CREATE TABLE business_insights (
    id VARCHAR(255) PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    
    -- Insight Classification
    type insight_type NOT NULL,
    category VARCHAR(255) NOT NULL,
    priority insight_priority NOT NULL,
    confidence FLOAT NOT NULL,
    
    -- Insight Content
    title VARCHAR(500) NOT NULL,
    description TEXT,
    actionable BOOLEAN DEFAULT FALSE,
    recommendations JSON,
    
    -- Impact Analysis
    potential_impact DECIMAL(15,2),
    timeframe VARCHAR(255),
    effort VARCHAR(255),
    
    -- Data Sources
    data_points JSON,
    related_entities JSON,
    
    -- User Interaction
    viewed BOOLEAN DEFAULT FALSE,
    viewed_at TIMESTAMP NULL,
    action_taken VARCHAR(255),
    user_feedback JSON,
    
    -- Lifecycle
    is_active BOOLEAN DEFAULT TRUE,
    expires_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    
    INDEX idx_business_insights_tenant (tenant_id),
    INDEX idx_business_insights_type (tenant_id, type),
    INDEX idx_business_insights_priority (tenant_id, priority),
    INDEX idx_business_insights_active (tenant_id, is_active),
    INDEX idx_business_insights_created (tenant_id, created_at)
);

-- Financial KPIs with AI predictions
CREATE TABLE financial_kpis (
    id VARCHAR(255) PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    
    -- KPI Definition
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    calculation JSON NOT NULL,
    
    -- Current Values
    current_value DECIMAL(20,8) NOT NULL,
    previous_value DECIMAL(20,8),
    target_value DECIMAL(20,8),
    benchmark_value DECIMAL(20,8),
    
    -- Trends
    trend VARCHAR(50),
    change_percent FLOAT,
    
    -- AI Predictions
    predicted_value DECIMAL(20,8),
    prediction_confidence FLOAT,
    
    period TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    
    INDEX idx_financial_kpis_tenant (tenant_id),
    INDEX idx_financial_kpis_category (tenant_id, category),
    INDEX idx_financial_kpis_period (tenant_id, period),
    INDEX idx_financial_kpis_trends (tenant_id, category, period DESC)
);

-- Enhanced entries table with AI fields
ALTER TABLE entries 
ADD COLUMN business_context_id VARCHAR(255),
ADD COLUMN predictive_factors JSON,
ADD COLUMN semantic_categories JSON,
ADD COLUMN relationship_graph JSON,
ADD COLUMN impact_score FLOAT,
ADD COLUMN risk_score FLOAT,
ADD COLUMN seasonality_factors JSON,
ADD COLUMN user_behavior_context JSON,
ADD COLUMN automation_level automation_level DEFAULT 'MANUAL',
ADD COLUMN learning_feedback JSON;

-- Add indexes for AI-enhanced queries
CREATE INDEX idx_entries_ai_metadata ON entries USING GIN (ai_insights);
CREATE INDEX idx_entries_automation_level ON entries (tenant_id, automation_level);
CREATE INDEX idx_entries_impact_score ON entries (tenant_id, impact_score DESC);
CREATE INDEX idx_entries_risk_score ON entries (tenant_id, risk_score DESC);
CREATE INDEX idx_entries_semantic ON entries USING GIN (semantic_categories);

-- AI Conversation History for learning
CREATE TABLE ai_conversation_history (
    id VARCHAR(255) PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    session_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255),
    
    -- Conversation Data
    query TEXT NOT NULL,
    intent VARCHAR(255),
    entities JSON,
    response JSON NOT NULL,
    confidence FLOAT NOT NULL,
    
    -- Performance Tracking
    execution_time INTEGER, -- milliseconds
    feedback VARCHAR(50), -- positive, negative, neutral
    user_rating INTEGER, -- 1-5 scale
    
    -- Learning Data
    correction_applied BOOLEAN DEFAULT FALSE,
    correction_details JSON,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    
    INDEX idx_conversation_tenant (tenant_id),
    INDEX idx_conversation_session (tenant_id, session_id),
    INDEX idx_conversation_intent (tenant_id, intent),
    INDEX idx_conversation_feedback (tenant_id, feedback),
    INDEX idx_conversation_created (tenant_id, created_at)
);

-- AI Training Data for model improvement
CREATE TABLE ai_training_data (
    id VARCHAR(255) PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    model_type VARCHAR(255) NOT NULL,
    
    -- Training Features
    input_features JSON NOT NULL,
    expected_output JSON NOT NULL,
    actual_output JSON,
    
    -- Validation
    is_validated BOOLEAN DEFAULT FALSE,
    validated_by VARCHAR(255),
    validated_at TIMESTAMP NULL,
    
    -- Quality Metrics
    confidence_score FLOAT,
    accuracy_contribution FLOAT,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    
    INDEX idx_training_data_tenant (tenant_id),
    INDEX idx_training_data_model (tenant_id, model_type),
    INDEX idx_training_data_validated (tenant_id, is_validated),
    INDEX idx_training_data_created (tenant_id, created_at)
);

-- Business Intelligence Cache for performance
CREATE TABLE bi_cache (
    id VARCHAR(255) PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    cache_key VARCHAR(500) NOT NULL,
    query_hash VARCHAR(255) NOT NULL,
    
    -- Cached Data
    result JSON NOT NULL,
    metadata JSON,
    
    -- Cache Management
    expires_at TIMESTAMP NOT NULL,
    hit_count INTEGER DEFAULT 0,
    last_accessed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    
    UNIQUE KEY unique_tenant_cache (tenant_id, cache_key),
    INDEX idx_bi_cache_tenant (tenant_id),
    INDEX idx_bi_cache_expires (expires_at),
    INDEX idx_bi_cache_hash (tenant_id, query_hash)
);

-- AI Model Registry
CREATE TABLE ai_model_registry (
    id VARCHAR(255) PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    
    -- Model Information
    model_name VARCHAR(255) NOT NULL,
    model_type VARCHAR(255) NOT NULL,
    version VARCHAR(50) NOT NULL,
    
    -- Model Configuration
    parameters JSON NOT NULL,
    features JSON NOT NULL,
    
    -- Performance Metrics
    accuracy FLOAT,
    precision_score FLOAT,
    recall_score FLOAT,
    f1_score FLOAT,
    
    -- Deployment Status
    status VARCHAR(50) DEFAULT 'training', -- training, active, deprecated
    deployed_at TIMESTAMP NULL,
    last_trained TIMESTAMP NULL,
    
    -- Model Artifacts
    model_path VARCHAR(500),
    artifacts JSON,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    
    INDEX idx_model_registry_tenant (tenant_id),
    INDEX idx_model_registry_type (tenant_id, model_type),
    INDEX idx_model_registry_status (tenant_id, status),
    INDEX idx_model_registry_version (tenant_id, model_name, version)
);