-- AlterTable
ALTER TABLE `tenants` ADD COLUMN `companyId` VARCHAR(191) NULL,
    ADD COLUMN `dateFormat` VARCHAR(191) NOT NULL DEFAULT 'dd MMM yyyy',
    ADD COLUMN `fiscalYearEnd` INTEGER NOT NULL DEFAULT 12,
    ADD COLUMN `fiscalYearStart` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `fiscalYearStartDay` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `industry` VARCHAR(191) NULL,
    ADD COLUMN `language` VARCHAR(191) NOT NULL DEFAULT 'English',
    ADD COLUMN `location` VARCHAR(191) NULL,
    ADD COLUMN `logo` VARCHAR(191) NULL,
    ADD COLUMN `reportBasis` ENUM('ACCRUAL', 'CASH') NOT NULL DEFAULT 'ACCRUAL',
    ADD COLUMN `timezone` VARCHAR(191) NOT NULL DEFAULT 'Asia/Rangoon';
